export const RESERVATION_FAILURE = "RESERVATION_FAILURE";
export const RESERVATION_SUCCESS = "RESERVATION_SUCCESS";
export const PROPERTIES_SUCCESS = "PROPERTIES_SUCCESS";
// EMPLOYEES_SUCCESS is also used in Properties
export const EMPLOYEES_SUCCESS = "EMPLOYEES_SUCCESS";
export const RESERVATION_STARTED = "RESERVATION_STARTED";
export const RESERVATION_COUNT_SUCCESS = "RESERVATION_COUNT_SUCCESS";
export const RESERVATION_SINGLE_SUCCESS = "RESERVATION_SINGLE_SUCCESS";
export const PROPERTY_SUCCESS = "PROPERTY_SUCCESS";
