export const REGISTER_USER_STARTED = "REGISTER_USER_STARTED";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REIGSTER_USER_FAILURE = "REIGSTER_USER_FAILURE";
export const COUNTS_STARTED = "COUNTS_STARTED";
export const COUNTS_SUCCESS = "COUNTS_SUCCESS";
export const COUNTS_FAILURE = "COUNTS_FAILURE";
export const USER_ROLE_SUCCESS = "USER_ROLE_SUCCESS";
export const DASHBOARD_FETCH_EMPLOYEES_STARTED =
  "DASHBOARD_FETCH_EMPLOYEES_STARTED";
export const DASHBOARD_FETCH_EMPLOYEES_SUCCESS =
  "DASHBOARD_FETCH_EMPLOYEES_SUCCESS";
export const DASHBOARD_FETCH_EMPLOYEES_FAILURE =
  "DASHBOARD_FETCH_EMPLOYEES_FAILURE";
