export const REGISTER_USER_STARTED = "REGISTER_USER_STARTED";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REIGSTER_USER_FAILURE = "REIGSTER_USER_FAILURE";
export const COUNTS_SUCCESS = "COUNTS_SUCCESS";
export const COUNTS_FAILURE = "COUNTS_FAILURE";
export const USER_ROLE_SUCCESS = "USER_ROLE_SUCCESS";
