export const FETCH_PROPERTY_ATTEMPT = "PROPERTY_STARTED";
export const FETCH_PROPERTY_SUCCESS = "PROPERTY_SUCCESS";
export const FETCH_PROPERTY_FAILURE = "PROPERTY_FAILURE";
export const FETCH_PROPERTIES_SUCCESS = "PROPERTIES_SUCCESS";
export const UPDATE_PROPERTY_STARTED = "UPDATE_PROPERTY_STARTED";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_FAILURE = "UPDATE_PROPERTY_FAILURE";
