export const PROPERTY_STARTED = "PROPERTY_STARTED";
export const PROPERTY_FAILURE = "PROPERTY_FAILURE";
export const FETCH_PROPERTY_SUCCESS = "PROPERTY_SUCCESS";
export const FETCH_PROPERTIES_SUCCESS = "PROPERTIES_SUCCESS";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const PROPERTY_COUNT_SUCCESS = "PROPERTY_COUNT_SUCCESS";
// EMPLOYEES_SUCCESS is also used in Reservation
export const EMPLOYEES_SUCCESS = "EMPLOYEES_SUCCESS";

export const FETCH_RESERVATIONS_SUCCESS = "RESERVATIONS_SUCCESS";

export const TASK_SUCCESS = "TASK_SUCCESS";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const USER_STARTED = "USER_STARTED";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
