export const EMPLOYEE_FAILURE = "EMPLOYEE_FAILURE";
export const EMPLOYEE_SUCCESS = "EMPLOYEE_SUCCESS";
export const EMPLOYEE_STARTED = "EMPLOYEE_STARTED";
export const EMPLOYEE_PROPERTY_STARTED = "EMPLOYEE_PROPERTY_STARTED";
export const EMPLOYEE_UPDATE_PROPERTY_SUCCESS =
  "EMPLOYEE_UPDATE_PROPERTY_SUCCESS";
export const EMPLOYEE_PROPERTY_FAILURE = "EMPLOYEE_PROPERTY_FAILURE";
export const SENDGRID_STARTED = "SENDGRID_STARTED";
export const SENDGRID_SUCCESS = "SENDGRID_SUCCESS";
export const SENDGRID_FAILURE = "SENDGRID_FAILURE";
