export const EMPLOYEE_FAILURE = 'EMPLOYEE_FAILURE';
export const EMPLOYEE_SUCCESS = 'EMPLOYEE_SUCCESS';
export const EMPLOYEE_STARTED = 'EMPLOYEE_STARTED';
export const NUM_EMPLOYEE_SUCCESS = 'NUM_EMPLOYEE_SUCCESS';
export const NUM_EMPLOYEE_FAIL = 'NUM_EMPLOYEE_FAIL';
