export const FETCH_TASK_ATTEMPT = "TASK_STARTED";
export const FETCH_TASK_SUCCESS = "TASK_SUCCESS";
export const FETCH_TASK_FAILURE = "TASK_FAILURE";
export const PROPERTIES_SUCCESS = "PROPERTIES_SUCCESS";
export const EMPLOYEES_SUCCESS = "EMPLOYEES_SUCCESS";
export const RESERVATIONS_SUCCESS = "RESERVATIONS_SUCCESS";
export const TASK_COUNT_SUCCESS = "TASK_COUNT_SUCCESS";
