export const CHECKOUT_STARTED = "CHECKOUT_STARTED";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_ERROR = "CHECKOUT_ERROR";

export const FETCH_RESERVATION_STARTED = "FETCH_RESERVATION_STARTED";
export const FETCH_RESERVATION_SUCCESS = "FETCH_RESERVATION_SUCCESS";
export const FETCH_RESERVATION_ERROR = "FETCH_RESERVATION_ERROR";

export const FETCH_PROPERTY_STARTED = "FETCH_PROPERTY_STARTED";
export const FETCH_PROPERTY_SUCCESS = "FETCH_PROPERTY_SUCCESS";
export const FETCH_PROPERTY_FAILURE = "FETCH_PROPERTY_FAILURE";

export const FETCH_EMPLOYEE_STARTED = "FETCH_EMPLOYEE_STARTED";
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_ERROR = "FETCH_EMPLOYEE_ERROR";

export const CHECKOUT_PROPERTY_STARTED = "CHECKOUT_PROPERTY_STARTED";
export const CHECKOUT_PROPERTY_SUCCESS = "CHECKOUT_PROPERTY_SUCCESS";
export const CHECKOUT_PROPERTY_ERROR = "CHECKOUT_PROPERTY_ERROR";
