export const CHECKOUT_STARTED = "CHECKOUT_STARTED";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_ERROR = "CHECKOUT_ERROR";

export const FETCH_RESERVATION_STARTED = "FETCH_RESERVATION_STARTED";
export const FETCH_RESERVATION_SUCCESS = "FETCH_RESERVATION_SUCCESS";
export const FETCH_RESERVATION_ERROR = "FETCH_RESERVATION_ERROR";
