export const CHECKOUT_STARTED = "CHECKOUT_STARTED";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_ERROR = "CHECKOUT_ERROR";

export const RESERVATION_STARTED = "RESERVATION_STARTED";
export const RESERVATION_SUCCESS = "RESERVATION_SUCCESS";
export const RESERVATION_ERROR = "RESERVATION_ERROR";

export const PROPERTY_STARTED = "PROPERTY_STARTED";
export const PROPERTY_SUCCESS = "PROPERTY_SUCCESS";
export const PROPERTY_FAILURE = "PROPERTY_FAILURE";

export const EMPLOYEE_STARTED = "EMPLOYEE_STARTED";
export const EMPLOYEE_SUCCESS = "EMPLOYEE_SUCCESS";
export const EMPLOYEE_ERROR = "EMPLOYEE_ERROR";
